# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OneWrapSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneWrapSDKDemo
  pod 'Google-Mobile-Ads-SDK', '9.6.0'
  pod 'OpenWrapSDK', '2.7.0'
  pod 'AdMobPubMaticAdapter', '2.1.1'

  target 'OneWrapSDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OneWrapSDKDemoUITests' do
    # Pods for testing
  end

end
